<a href="https://colab.research.google.com/github/MSR806/DL/blob/master/PytorchIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

#**Intialise tensors**

In [ ]:
x = torch.ones(3,2)
print(x)
x = torch.zeros(3,2)
print(x)
x = torch.rand(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.0660, 0.5827],
        [0.5846, 0.0253],
        [0.2127, 0.7580]])


In [ ]:
x = torch.empty(3,2)
print(x)
x = torch.zeros_like(x)
print(x)

tensor([[5.1632e-36, 0.0000e+00],
        [3.3631e-44, 0.0000e+00],
        [       nan, 6.1657e-44]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [ ]:
x = torch.linspace(0, 1, steps = 5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [ ]:
x = torch.tensor([[1,2],
                  [3, 4],
                  [5,6]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


#**Slicing tensors**

In [ ]:
print(x.size())
print(x[:,1])
print(x[0,:])

torch.Size([3, 2])
tensor([2, 4, 6])
tensor([1, 2])


In [ ]:
y = x[1,1]
print(y)
print(y.item())

tensor(4)
4


In [ ]:
print(x.item())

ValueError: ignored

#**Reshaping tensors**

In [ ]:
print(x)
y = x.view(2,3)
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
y = x.view(6, -1)
print(y)
y = x.view(6, 1)
print(y)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


#**Simple Tensor Operations**

In [ ]:
x = torch.ones(3,2)
y = torch.ones(3,2)
z = x + y
print(z)
z = x - y
print(z)
z = x * y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [ ]:
z = y.add(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


Adding in place

In [ ]:
z = y.add_(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


#**Numpy <> Pytorch**

In [ ]:
x_np = x.numpy()
print(type(x),type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
a = np.random.randn(5)
print(a)
a_pt = torch.from_numpy(a)
print(type(a),type(a_pt))
print(a_pt)

[-1.12637876 -1.35509264 -0.37622986 -0.80225175 -1.54590669]
<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([-1.1264, -1.3551, -0.3762, -0.8023, -1.5459], dtype=torch.float64)


In [ ]:
np.add(a, 1, out=a)
print(a)
print(a_pt)

[-0.12637876 -0.35509264  0.62377014  0.19774825 -0.54590669]
tensor([-0.1264, -0.3551,  0.6238,  0.1977, -0.5459], dtype=torch.float64)


In [ ]:
%%time
for i in range(10):
  a = np.random.randn(10000,10000)
  b = np.random.randn(10000,10000)
  c = a + b
  #c = a*b
  #c = np.matmul(a,b)

CPU times: user 1min 36s, sys: 1.41 s, total: 1min 37s
Wall time: 1min 37s


In [ ]:
%%time
for i in range(10):
  a = torch.randn(10000,10000)
  b = torch.randn(10000,10000)
  c = a + b
  #c = a*b
  #c = torch.matmul(a,b)

CPU times: user 22.7 s, sys: 12.6 ms, total: 22.7 s
Wall time: 22.7 s


#**CUDA Support**

In [56]:
print(torch.cuda.device_count())

1


In [57]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

Tesla T4


In [58]:
cuda0 = torch.device('cuda:0')

In [ ]:
a = torch.ones(3, 2, device=cuda0)
b = torch.ones(3, 2, device=cuda0)
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [ ]:
%%time
for i in range(10):
  a = torch.randn(10000,10000, device=cuda0)
  b = torch.randn(10000,10000, device=cuda0)
  b.add_(a)

CPU times: user 983 µs, sys: 0 ns, total: 983 µs
Wall time: 984 µs


In [62]:
%%time
for i in range(10):
  a = torch.randn(10000,10000, device=cuda0)
  b = torch.randn(10000,10000, device=cuda0)
  torch.matmul(b,a)

CPU times: user 2.08 ms, sys: 1 µs, total: 2.08 ms
Wall time: 1.51 ms


The above code will take ~9min with Numpy and ~4min with Pytorch on CPU

#**Autograd**

In [7]:
x = torch.ones(3,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [10]:
y = x + 6
print(y)

tensor([[7., 7.],
        [7., 7.],
        [7., 7.]], grad_fn=<AddBackward0>)


In [11]:
z = y*y + 1
print(z)

tensor([[50., 50.],
        [50., 50.],
        [50., 50.]], grad_fn=<AddBackward0>)


In [12]:
t = torch.sum(z)
print(t)

tensor(300., grad_fn=<SumBackward0>)


In [13]:
t.backward()

In [14]:
print(x.grad)

tensor([[14., 14.],
        [14., 14.],
        [14., 14.]])


In [16]:
x = torch.ones(3,2, requires_grad=True)
y = x + 5
r = 1/(1 + torch.exp(-y))
print(r)
s = torch.sum(r)
s.backward()
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [17]:
x = torch.ones(3,2, requires_grad=True)
y = x + 5
r = 1/(1 + torch.exp(-y))
a = torch.ones(3,2)
r.backward(a)
print(x.grad)

tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


$\frac{\partial s}{\partial x} = \frac{\partial s}{\partial r}.\frac{\partial r}{\partial x}$

For the above code a represents the $\frac{\partial s}{\partial r}$ and then $x.grad$ directly gives $\frac{\partial s}{\partial x}$

#**Autograd Example**

In [39]:
x  = torch.randn(20, 1, requires_grad=True)
y = 3*x - 2

In [40]:
w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

y_hat = w*x + b

loss = torch.sum((y_hat - y)**2)

In [41]:
print(loss)

tensor(206.5119, grad_fn=<SumBackward0>)


In [42]:
loss.backward()

In [43]:
print(w.grad, b.grad)

tensor([-45.4035]) tensor([107.4056])


#**Do it in a Loop**

In [72]:
%%time

learning_rate = 0.001
N = 1000000
epochs = 200
w = torch.rand(N, requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

#print(torch.mean(w).item(), b.item())

for i in range(epochs):
  x = torch.randn(N)
  y = torch.dot(3*torch.ones(N), x) - 2

  y_hat = torch.dot(w,x) + b
  loss = torch.sum((y_hat - y)**2)

  loss.backward()

  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad
  
  w.grad.zero_()
  b.grad.zero_()

#print(torch.mean(w).item(), b.item())

CPU times: user 3.6 s, sys: 57.7 ms, total: 3.66 s
Wall time: 3.66 s


In [73]:
%%time

learning_rate = 0.001
N = 1000000
epochs = 200
w = torch.rand(N, requires_grad=True, device=cuda0)
b = torch.tensor([1.], requires_grad=True, device=cuda0)

#print(torch.mean(w).item(), b.item())

for i in range(epochs):
  x = torch.randn(N, device=cuda0)
  y = torch.dot(3*torch.ones(N, device=cuda0), x) - 2

  y_hat = torch.dot(w,x) + b
  loss = torch.sum((y_hat - y)**2)

  loss.backward()

  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad
  
  w.grad.zero_()
  b.grad.zero_()

#print(torch.mean(w).item(), b.item())

CPU times: user 161 ms, sys: 15.9 ms, total: 177 ms
Wall time: 177 ms
