<a href="https://colab.research.google.com/github/MSR806/DL/blob/master/PytorchIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

#**Intialise tensors**

In [2]:
x = torch.ones(3,2)
print(x)
x = torch.zeros(3,2)
print(x)
x = torch.rand(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.0660, 0.5827],
        [0.5846, 0.0253],
        [0.2127, 0.7580]])


In [4]:
x = torch.empty(3,2)
print(x)
x = torch.zeros_like(x)
print(x)

tensor([[5.1632e-36, 0.0000e+00],
        [3.3631e-44, 0.0000e+00],
        [       nan, 6.1657e-44]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [6]:
x = torch.linspace(0, 1, steps = 5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [8]:
x = torch.tensor([[1,2],
                  [3, 4],
                  [5,6]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


#**Slicing tensors**

In [10]:
print(x.size())
print(x[:,1])
print(x[0,:])

torch.Size([3, 2])
tensor([2, 4, 6])
tensor([1, 2])


In [11]:
y = x[1,1]
print(y)
print(y.item())

tensor(4)
4


In [12]:
print(x.item())

ValueError: ignored

#**Reshaping tensors**

In [13]:
print(x)
y = x.view(2,3)
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [14]:
y = x.view(6, -1)
print(y)
y = x.view(6, 1)
print(y)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


#**Simple Tensor Operations**

In [15]:
x = torch.ones(3,2)
y = torch.ones(3,2)
z = x + y
print(z)
z = x - y
print(z)
z = x * y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [16]:
z = y.add(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


Adding in place

In [17]:
z = y.add_(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


#**Numpy <> Pytorch**

In [18]:
x_np = x.numpy()
print(type(x),type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
a = np.random.randn(5)
print(a)
a_pt = torch.from_numpy(a)
print(type(a),type(a_pt))
print(a_pt)

[-1.12637876 -1.35509264 -0.37622986 -0.80225175 -1.54590669]
<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([-1.1264, -1.3551, -0.3762, -0.8023, -1.5459], dtype=torch.float64)


In [20]:
np.add(a, 1, out=a)
print(a)
print(a_pt)

[-0.12637876 -0.35509264  0.62377014  0.19774825 -0.54590669]
tensor([-0.1264, -0.3551,  0.6238,  0.1977, -0.5459], dtype=torch.float64)


In [25]:
%%time
for i in range(10):
  a = np.random.randn(10000,10000)
  b = np.random.randn(10000,10000)
  c = a + b
  #c = a*b
  #c = np.matmul(a,b)

CPU times: user 1min 36s, sys: 1.41 s, total: 1min 37s
Wall time: 1min 37s


In [26]:
%%time
for i in range(10):
  a = torch.randn(10000,10000)
  b = torch.randn(10000,10000)
  c = a + b
  #c = a*b
  #c = torch.matmul(a,b)

CPU times: user 22.7 s, sys: 12.6 ms, total: 22.7 s
Wall time: 22.7 s


#**CUDA Support**

In [2]:
print(torch.cuda.device_count())

1


In [3]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

Tesla T4


In [4]:
cuda0 = torch.device('cuda:0')

In [6]:
a = torch.ones(3, 2, device=cuda0)
b = torch.ones(3, 2, device=cuda0)
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [8]:
%%time
for i in range(10):
  a = torch.randn(10000,10000, device=cuda0)
  b = torch.randn(10000,10000, device=cuda0)
  b.add_(a)

CPU times: user 983 µs, sys: 0 ns, total: 983 µs
Wall time: 984 µs


In [9]:
%%time
for i in range(10):
  a = torch.randn(10000,10000, device=cuda0)
  b = torch.randn(10000,10000, device=cuda0)
  torch.matmul(b,a)

CPU times: user 3.81 ms, sys: 58 µs, total: 3.87 ms
Wall time: 11.6 ms


The above code will take ~9min with Numpy and ~4min with Pytorch on CPU

#**Autograd**